- hosts: URL_shortener
  name: Configure file system, set data directory for postgres
  remote_user: "{{ USER }}"
  gather_facts: no
  vars_files:
    - ../vars.yml
  tasks:
    - name: Create postgres data directory on mounted volume and copy files from default directory
      args:
        executable: /bin/bash
      register: create_postgres_data_directory
      shell: |
        postgres_path="{{ FS_MOUNT_PATH }}/postgresql/13/data"

        if [ -d "$postgres_path" ]
        then
          echo "$postgres_path already exist."
        else
          sudo mkdir -p $postgres_path
          sudo chown -R postgres:postgres $postgres_path
          sudo chmod 700 $postgres_path
        fi

        # IMPORTANT!!! Do not copy files if they already exist, otherwise postgres data will be overwritten
        sudo rsync -av --ignore-existing /var/lib/postgresql/13/main/ $postgres_path
    - debug: var=create_postgres_data_directory.stdout_lines
    - debug: var=create_postgres_data_directory.stderr_lines
    - name: Configure postgresql.conf
      args:
        executable: /bin/bash
      register: postgres_conf_data_directory
      shell: |
        postgres_path="{{ FS_MOUNT_PATH }}/postgresql/13/data"

        sudo mkdir -p /etc/postgresql/13/main/conf.d

        cat <<EOF | sudo tee /etc/postgresql/13/main/conf.d/postgresql.conf > /dev/null 
        #------------------------------------------------------------------------------
        # FILE LOCATIONS
        #------------------------------------------------------------------------------
        data_directory = '$postgres_path'

        #------------------------------------------------------------------------------
        # REPORTING AND LOGGING
        #------------------------------------------------------------------------------
        # - Where to Log -
        log_destination = 'stderr'
        logging_collector = on
        log_directory = 'log'
        log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
        log_file_mode = 0600
        log_rotation_age = 1d
        log_rotation_size = 10MB

        # - When to Log -
        log_min_messages = warning
        log_min_error_statement = error
        log_min_duration_sample = 100
        log_statement_sample_rate = 0.5
        log_transaction_sample_rate = 0.5

        # - What to Log -
        log_duration = on
        log_line_prefix = '%m [%p] [%d] %u %a'
        EOF
    - debug: var=postgres_conf_data_directory.stdout_lines
    - debug: var=postgres_conf_data_directory.stderr_lines
    - name: Configure postgres systemd
      args:
        executable: /bin/bash
      register: postgres_systemd
      shell: |
        postgres_path="{{ FS_MOUNT_PATH }}/postgresql/13/data"

        sudo mkdir -p /etc/systemd/system/postgresql.service.d
        sudo touch /etc/systemd/system/postgresql.service.d/override.conf
        num_existing_line=$(sudo cat /etc/systemd/system/postgresql.service.d/override.conf | grep Environment=PGDATA=$postgres_path | wc -l)
        
        if [ "$num_existing_line" -eq 0 ]
        then
          cat <<EOF | sudo tee -a /etc/systemd/system/postgresql.service.d/override.conf > /dev/null
          [Service]
          Environment=PGDATA=$postgres_path
        EOF
        else
          echo "PGDATA is already added to /etc/systemd/system/postgresql.service.d/override.conf"
        fi

        sudo systemctl daemon-reload
        sudo systemctl restart postgresql.service
    - debug: var=postgres_systemd.stdout_lines
    - debug: var=postgres_systemd.stderr_lines
