- hosts: URL_shortener
  name: Let's encrypt
  remote_user: "{{ user }}"
  gather_facts: no
  vars_files:
    - ./vars.yml
  tasks:
    - name: Install let's encrypt for nginx
      args:
        executable: /bin/bash
      shell: |  
        sudo snap install --classic certbot

        # check if certificate is already installed
        cert_domains=($(sudo certbot certificates | grep Domains | sed "s~^[[:space:]]*~~" | cut -d ' ' -f 2))

        for cert_domain in "${cert_domains[@]}"
        do
          if [ "cert_domain" == {{ domain }} ]
          then
            echo "Certificate is already installed for {{ domain }}"
            return 0
          fi
        done
        sudo certbot --nginx -d {{ domain }} -d {{ domain }} --non-interactive --agree-tos --email {{ admin_email }}
        sudo ln -sf /etc/nginx/sites-available/{{ domain }} /etc/nginx/sites-enabled/
        sudo certbot renew --dry-run
        sudo systemctl reload nginx
      
