name: Health check for EC2 and URL shortener
on:
  schedule:
    - cron: '5,35,55 11-14 * * 1-5' # weekdays
    - cron: '5,35,55 3-14 * * 0,6' # weekends, 0 = sunday
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'info' 
        type: choice
        options:
        - info
        - warning
        - debug
env:
  URL_SHORTENER_HOST_NAME: ${{ secrets.URL_SHORTENER_HOST_NAME }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
jobs:
  ec2_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if EC2 is running
        run: |
          curl $URL_SHORTENER_HOST_NAME
  notify_unsuccessful_ec2_health_check:
    runs-on: ubuntu-latest
    needs: [ec2_health_check]
    if: ${{ failure() }}
    steps:
      - name: Send slack notification EC2 is not running
        run: |
          now=$(date +%Y-%m-%dT%H:%M:%S)
          payload=$(echo "{\"text\":\"URL shortener infra: Health check for $URL_SHORTENER_HOST_NAME failed at <DATE>. Workflow: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" | sed "s~<DATE>~$now~")
          curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK
  url_shortener_health_check:
    runs-on: ubuntu-latest
    needs: [ec2_health_check]
    steps:
      - name: Configure basic tools
        run: |
          sudo apt -y install jq
      - name: Check if URL shortener is running
        run: |
          curl $URL_SHORTENER_HOST_NAME/healthz
          if [ $? -ne 0 ]
          then
            now=$(date +%Y-%m-%dT%H:%M:%S)
            payload=$(echo "{\"text\":\"URL shortener infra: Health check for $URL_SHORTENER_HOST_NAME/healthz failed at <DATE>. Workflow: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" | sed "s~<DATE>~$now~")
            curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK
            exit 1
          fi 
      - name: Check if URL shortener postgres is running
        run: |
          health_check_url="$URL_SHORTENER_HOST_NAME/healthz?postgres"
          is_postgres_running=$(curl $health_check_url | jq '.payload.postgres != null')
          if [ $is_postgres_running = false ]
          then
            now=$(date +%Y-%m-%dT%H:%M:%S)
            payload=$(echo "{\"text\":\"URL shortener infra: Health check for $health_check_url failed at <DATE>. Workflow: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" | sed "s~<DATE>~$now~")
            curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK
            exit 1
          fi
      - name: Check if URL shortener redis is running
        run: |
          health_check_url="$URL_SHORTENER_HOST_NAME/healthz?redis"
          is_redis_running=$(curl $health_check_url | jq '.payload.redis != null')
          if [ $is_redis_running = false ]
          then
            now=$(date +%Y-%m-%dT%H:%M:%S)
            payload=$(echo "{\"text\":\"URL shortener infra: Health check for $health_check_url failed at <DATE>. Workflow: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" | sed "s~<DATE>~$now~")
            curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK
            exit 1
          fi
          
      
      