name: Stop URL shortener
on:
  schedule:
    # Run a few times for each schedule, just in case there some transient errors occurs during the run
    - cron: '50 13 * * 1-5' # weekdays
    - cron: '50 3 * * 0,6' # weekends, 0 = sunday
    - cron: '50 14 * * *'  # weekends, 0 = sunday
jobs:
  stop_url_shortener:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DOMAIN: ${{ secrets.DOMAIN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      URL_SHORTENER_HOST_NAME: ${{ secrets.URL_SHORTENER_HOST_NAME }}
    steps:
      - uses: actions/checkout@v3
      - name: Check if EC2 is already stopped
        run: |
          curl $URL_SHORTENER_HOST_NAME/healthz
          if [ $? -ne 0 ]
          then
            echo "EC2 is already stopped"
            now=$(date +%Y-%m-%dT%H:%M:%S)
            payload=$(echo "{\"text\":\"EC2 is already stopped at <DATE>\"}" | sed "s~<DATE>~$now~")
            curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK
          fi
          curl $URL_SHORTENER_HOST_NAME/healthz
      - name: Create AWS config and credentials
        if: ${{ success() }}
        run: |
          pwd
          ls -la

          mkdir ~/.aws/
          cat << EOF > ~/.aws/config
          [default]
          region = $AWS_REGION
          output = json
          EOF
          chmod 600 ~/.aws/config

          cat << EOF > ~/.aws/credentials
          [default]
          aws_access_key_id = $AWS_ACCESS_KEY
          aws_secret_access_key = $AWS_SECRET_KEY
          EOF
          chmod 600 ~/.aws/credentials
      - name: Run stop script
        run: | 
          cd instances
          ./scripts/stop.sh $DOMAIN
      - name: Send slack notification
        run: |
          now=$(date +%Y-%m-%dT%H:%M:%S)
          payload=$(echo "{\"text\":\"Successfully stopped EC2 at <DATE>\"}" | sed "s~<DATE>~$now~")
          curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK
